In [2]:
import pandas as pd

gitCloudRepo='https://github.com/PUBPOL-542/guided1/raw/main/'
fileName="povertyWA.xlsx"

DFcsv1=pd.read_excel(gitCloudRepo + fileName)
DFcsv1

,year,sample,serial,cbserial,hhwt,cluster,statefip,countyfip,strata,gq,...,race,raced,speakeng,educ,educd,empstat,empstatd,uhrswork,poverty,energyburden
0,2021,2021 acs,1371772,2021000000011,15,2021013717721,washington,35,1180153,households under 1970 definition,...,white,white,"yes, speaks only english",1 year of college,"1 or more years of college credit, no degree",employed,at work,40,501,0.138040
1,2021,2021 acs,1371773,2021000000069,84,2021013717731,washington,63,1050153,households under 1970 definition,...,white,white,"yes, speaks only english",4 years of college,bachelor's degree,employed,at work,8,40,0.867132
2,2021,2021 acs,1371773,2021000000069,84,2021013717731,washington,63,1050153,households under 1970 definition,...,white,white,"yes, speaks only english",1 year of college,"1 or more years of college credit, no degree",employed,at work,20,58,0.867132
3,2021,2021 acs,1371774,2021000000075,33,2021013717741,washington,0,1040053,households under 1970 definition,...,white,white,"yes, speaks only english",grade 12,regular high school diploma,not in labor force,not in labor force,NaN,51,2.855143
4,2021,2021 acs,1371775,2021000000083,297,2021013717751,washington,33,1161153,households under 1970 definition,...,white,white,"yes, speaks only english",1 year of college,"1 or more years of college credit, no degree",unemployed,unemployed,45,288,0.395842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59602,2021,2021 acs,1402572,2021001415650,187,2021014025721,washington,67,1140153,households under 1970 definition,...,white,white,"yes, speaks only english",grade 12,regular high school diploma,not in labor force,not in labor force,NaN,482,0.153536
59603,2021,2021 acs,1402573,2021001415666,229,2021014025731,washington,53,1150653,households under 1970 definition,...,other asian or pacific islander,samoan,"yes, speaks only english",grade 12,regular high school diploma,employed,at work,40,262,0.094118
59604,2021,2021 acs,1402573,2021001415666,229,2021014025731,washington,53,1150653,households under 1970 definition,...,two major races,white and black,"yes, speaks only english",grade 12,ged or alternative credential,employed,at work,40,262,0.094118
59605,2021,2021 acs,1402573,2021001415666,229,2021014025731,washington,53,1150653,households under 1970 definition,...,other asian or pacific islander,samoan,"yes, speaks only english",grade 12,regular high school diploma,not in labor force,not in labor force,NaN,262,0.094118
59606,2021,2021 acs,1402573,2021001415666,229,2021014025731,washington,53,1150653,households under 1970 definition,...,other asian or pacific islander,samoan,"yes, speaks very well",1 year of college,"1 or more years of college credit, no degree",not in labor force,not in labor force,NaN,262,0.094118

In [3]:
DFcsv1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59607 entries, 0 to 59606
Data columns (total 31 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          59607 non-null  int64
 1   sample        59607 non-null  object
 2   serial        59607 non-null  int64
 3   cbserial      59607 non-null  int64
 4   hhwt          59607 non-null  int64
 5   cluster       59607 non-null  int64
 6   statefip      59607 non-null  object
 7   countyfip     59607 non-null  int64
 8   strata        59607 non-null  int64
 9   gq            59607 non-null  object
 10  ownershp      59607 non-null  object
 11  ownershpd     59607 non-null  object
 12  costgas       59607 non-null  int64
 13  costwatr      59607 non-null  int64
 14  hhincome      59607 non-null  int64
 15  cinethh       59607 non-null  object
 16  pernum        59607 non-null  int64
 17  perwt         59607 non-null  int64
 18  famsize       59607 non-null  object
 19  sex           59607 non-null  object
 20  age           59607 non-null  int64
 21  race          59607 non-null  object
 22  raced         59607 non-null  object
 23  speakeng      59607 non-null  object
 24  educ          59607 non-null  object
 25  educd         59607 non-null  object
 26  empstat       59607 non-null  object
 27  empstatd      59607 non-null  object
 28  uhrswork      38483 non-null  object
 29  poverty       59607 non-null  int64
 30  energyburden  59607 non-null  float64
dtypes: float64(1), int64(14), object(16)
memory usage: 14.1+ MB